-- MySQL Script generated by MySQL Workbench
-- 05/01/15 15:11:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`club` (
  `id` INT NOT NULL,
  `clubName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`league`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`league` (
  `leaguecode` INT NOT NULL,
  `leaguetext` VARCHAR(45) NULL,
  `fieldsize` VARCHAR(45) NULL,
  `wertungsmodus_id` VARCHAR(45) NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`leaguecode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT NOT NULL,
  `leaguetype` VARCHAR(45) NULL,
  `leaguecode` VARCHAR(45) NULL,
  `leaguetext` VARCHAR(45) NULL,
  `fieldsize` VARCHAR(45) NULL,
  `wertungsmodus` VARCHAR(45) NULL,
  `wertungsmodus_id` VARCHAR(45) NULL,
  `eventtype` VARCHAR(45) NULL,
  `league_leaguecode` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_league1_idx` (`league_leaguecode` ASC),
  CONSTRAINT `fk_group_league1`
    FOREIGN KEY (`league_leaguecode`)
    REFERENCES `mydb`.`league` (`leaguecode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team` (
  `id` INT NOT NULL,
  `teamName` VARCHAR(45) NOT NULL,
  `club_id` INT NOT NULL,
  `leaguecode` VARCHAR(45) NOT NULL,
  `teamromancounter` VARCHAR(45) NULL,
  `group` INT NOT NULL,
  `grouptext` VARCHAR(45) NOT NULL,
  `league_leaguecode` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_team_club_idx` (`club_id` ASC),
  INDEX `fk_team_league1_idx` (`league_leaguecode` ASC),
  INDEX `fk_team_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_team_club`
    FOREIGN KEY (`club_id`)
    REFERENCES `mydb`.`club` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_league1`
    FOREIGN KEY (`league_leaguecode`)
    REFERENCES `mydb`.`league` (`leaguecode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game` (
  `id` INT NOT NULL,
  `season` VARCHAR(45) NOT NULL,
  `leaguetype` VARCHAR(45) NOT NULL,
  `leaguetext` VARCHAR(45) NOT NULL,
  `fieldsize` VARCHAR(45) NOT NULL,
  `played` TINYINT(1) NOT NULL,
  `goalshome` INT NULL,
  `goalsaway` INT NULL,
  `overtime` TINYINT(1) NULL,
  `penaltyshooting` TINYINT(1) NULL,
  `forfait` TINYINT(1) NULL,
  `canceled` TINYINT(1) NULL,
  `organizer` VARCHAR(45) NOT NULL,
  `organizerid` VARCHAR(45) NOT NULL,
  `eventtype` VARCHAR(45) NULL,
  `hometeamname` VARCHAR(45) NOT NULL,
  `hometeamid` VARCHAR(45) NOT NULL,
  `awayteamid` VARCHAR(45) NOT NULL,
  `awayteamname` VARCHAR(45) NOT NULL,
  `group` VARCHAR(45) NULL,
  `league_leaguecode` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_game_league1_idx` (`league_leaguecode` ASC),
  CONSTRAINT `fk_game_league1`
    FOREIGN KEY (`league_leaguecode`)
    REFERENCES `mydb`.`league` (`leaguecode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team_has_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team_has_game` (
  `team_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`team_id`, `game_id`),
  INDEX `fk_team_has_game_game1_idx` (`game_id` ASC),
  INDEX `fk_team_has_game_team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_team_has_game_team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_game_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
